curd/crudApplication/urls.py
from django.conf.urls import url
from .import views
urlpatterns = [
    url(r'^add/$',views.add_book ,name='add'),
    url(r'^show/$',views.show_book ,name='show'),
    url(r'^delete/(?P<book_id>\d+)/$',views.delete_book),
    url(r'^edit/(?P<book_id>\d+)/$',views.edit_record),
    url(r'^update/(?P<book_id>\d+)/$',views.update_record),
    url(r'^profile/(?P<book_id>\d+)/$',views.profile),
    url(r'^contact/$',views.contact,name='contact'),
]

curd/curd/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from .import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^crud/',include('crudApplication.urls')),
    url(r'^$' ,views.home,name='home')
]+ static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

curd/crudApplication/models.py
from django.db import models
from django.db.models.signals import post_save

# Create your models here.
class Book(models.Model):
    book_id = models.AutoField(primary_key=True)
    book_name = models.CharField(max_length=50)
    auther_name = models.CharField(max_length=30)
    price = models.IntegerField()
    publish_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.book_name

class BookProfile(models.Model):
    book = models.OneToOneField(Book,on_delete=models.CASCADE)
    image = models.ImageField(upload_to="book/images",default="")
    desc = models.TextField(max_length=200)

    def __str__(self):
        return self.book.book_name

def save_profile(sender, instance, **kwargs):
    BookProfile.objects.create(book=instance)
post_save.connect(save_profile, sender=Book)



class Contact(models.Model):
    msg_id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=50)
    email=models.CharField(max_length=50,default="")
    phone=models.CharField(max_length=50,default="")
    desc=models.CharField(max_length=500,default="")

    def __str__(self):
        return self.name

curd/crudApplication/forms.py
from django import forms
from .models import Book
class AddBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields ='__all__'

curd/crudApplication/views.py
from django.shortcuts import render,redirect
from .forms import AddBookForm
from .models import Book,BookProfile,Contact

# Create your views here.
def add_book(request):
    form= AddBookForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('show')
    return render(request,'add_book.html',{'form':form})

def show_book(request):
    form =Book.objects.all()
    return render(request,'show_books.html',{'form':form})

def delete_book(request, book_id):
    form = Book.objects.get(book_id=book_id)
    form.delete()
    return redirect("show")
def edit_record(request, book_id):
    form = Book.objects.get(book_id=book_id)
    return render(request, 'edit.html', {'form': form})

def update_record(request, book_id):
    record = Book.objects.get(book_id=book_id)
    form = AddBookForm(request.POST or None, instance=record)
    if(form.is_valid()):
        form.save()
        return redirect('show')
    return render(request, 'edit.html')

def profile(request,book_id):
    form = BookProfile.objects.get(book_id=book_id)
    return render(request, 'profile.html', {'form': form})

def contact(request):
    thanks = False
    if (request.method == 'POST'):
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        desc = request.POST.get('desc')
        contact = Contact(name=name, email=email, phone=phone, desc=desc)
        contact.save()
        thanks = True
    return render(request , 'contact.html',{'thanks':thanks})

curd/curd/views.py
from django.shortcuts import render

def home(request):
    return render(request,'home.html')

curd/crudApplication/templates/add_book.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>add_book</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script>
        <link rel="stylesheet" href="{% static 'js/bootstrap.min.js' %}">

    </script>
</head>
<body style="background-image:url({% static 'xyz2.jpg' %});">
<form action="" method="post">
    {% csrf_token %}
    <div class="container">
        <br>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <h3>Enter Details</h3>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Book Name:</label>
            <div class="col-sm-4">
                {{ form.book_name }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Auther Name:</label>
            <div class="col-sm-4">
                {{ form.auther_name }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Book Price:</label>
            <div class="col-sm-4">
                {{ form.price }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </div>
</form>
</body>
</html>

curd/crudApplication/templates/contact.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>show_books</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script>
        <link rel="stylesheet" href="{% static 'js/bootstrap.min.js' %}">
    </script>
    <script src="{% static 'jquery' %}"></script>

</head>
<body>
<div class="container my-4">
    <h3>Contact Us</h3>
    <form action="{% url 'contact' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="Name">Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="Enter your name">
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter your Email">
        </div>
        <div class="form-group">
            <label for="phone">Phone</label>
            <input type="tel" multiple class="form-control" id="phone" name="phone" placeholder="Enter your phone">
        </div>
        <div class="form-group">
            <label for="desc">How May I Help You</label>
            <textarea class="form-control" id="desc" name="desc" rows="3"></textarea>
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
</div>
</body>
<script>
    {% if thanks %}
    alert("thank for contact us i will cal you later");
    document.location='/';
    {% endif %}
</script>

curd/crudApplication/templates/edit.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Edit</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script>
        <link rel="stylesheet" href="{% static 'js/bootstrap.min.js' %}">
    </script>
</head>
<body style="background-image:url({% static 'xyz2.jpg' %});">
    <form method="post" class="post-form" action="/crud/update/{{form.book_id}}/">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Book Name:</label>
    <div class="col-sm-4">
        <input type="text" name="book_name" id="book_id" required maxlength="20" value="{{ form.book_name }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Auther Name:</label>
    <div class="col-sm-4">
        <input type="text" name="auther_name" id="aid" required maxlength="100" value="{{ form.auther_name }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Book Price:</label>
    <div class="col-sm-4">
        <input type="number" name="price" id="id_price" required  value="{{ form.price }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-success">Update</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

curd/crudApplication/templates/profile.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>profile</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script>
        <link rel="stylesheet" href="{% static 'js/bootstrap.min.js' %}">

    </script>
</head>
<body style="background-image:url({% static 'xyz2.jpg' %});">
<form action="" method="post">
    {% csrf_token %}
    <div class="container mt-4">

        <div class="form-group row">
            <div class="col-sm-4" style="color:red;">
                {{ form.book }}
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-4">
                <img src="/media/{{form.image}}" height="200" width="200" alt="">
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-4">
                {{ form.desc }}
            </div>
        </div>
    </div>
</form>
<br>
<br>
<center><a href="{% url 'show' %}" class="btn btn-primary">BACK</a></center>
</body>
</html>

curd/crudApplication/templates/show_books.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>show_books</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script>
        <link rel="stylesheet" href="{% static 'js/bootstrap.min.js' %}">


    </script>

</head>
<body style="background-image:url({% static 'xyz2.jpg' %});">
<div class="container mt-4">
    <form action="" method="post">
        {% csrf_token %}
        <table class="table table-striped table-bordered table-sm">
            <thead class="thead-dark">
            <tr>
                <th>
                    <mark>BOOK ID</mark>
                </th>
                <th>
                    <mark>BOOK Name</mark>
                </th>
                <th>
                    <mark>Auther Name</mark>
                </th>
                <th>
                    <mark>BOOK PRICE</mark>
                </th>
                <th>
                    <mark>VIEW BOOK</mark>
                </th>
                <th>
                    <mark>DELETE BOOK</mark>
                </th>
                <th>
                    <mark>EDIT BOOK</mark>
                </th>
            </tr>
            </thead>
            <tbody>
            {% for field in form %}
            <tr>
                <td>{{field.book_id}}</td>
                <td>{{field.book_name}}</td>
                <td>{{field.auther_name}}</td>
                <td><b>Rs.</b> {{field.price}}</td>
                <td><a href="/crud/profile/{{field.book_id}}">View</a></td>
                <td><a href="/crud/delete/{{field.book_id}}">Delete</a></td>
                <td><a href="/crud/edit/{{field.book_id}}">Edit</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <br>
        <br>
        <center><a href="{% url 'add' %}" class="btn btn-primary">Add New Record</a> <a href="{% url 'home' %}" class="btn btn-primary">Home</a></center>

    </form>
</div>
</body>
</html>

curd/templates/home.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    {% load static %}
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        body{
        background-image:url({% static 'xyz3.jpg' %});
    </style>
    <script>
        <link rel="stylesheet" href="{% static 'js/bootstrap.min.js' %}">
    </script>
</head>
<body class="d-flex flex-column h-100">
<header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">My Stationary</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'show' %}">Show Books</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contact' %}">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/admin">Admin Pannel</a>
                </li>
            </ul>
        </div>
    </nav>
</header>
</body>
</html>